export const OUTREACH_LANGUAGES = [
    "English",
    "French",
    "German",
    "Spanish",
    "Italian",
    "Portuguese",
    "Dutch",
    "Greek",
    "Polish",
    "Swedish",
    "Danish",
    "Finnish",
    "Norwegian",
    "Romanian",
    "Hungarian",
    "Czech",
    "Slovak",
    "Bulgarian",
    "Croatian",
    "Slovenian",
    "Estonian",
    "Latvian",
    "Lithuanian",
    "Irish",
    "Maltese",
    "Ukrainian",
] as const;

export type OutreachLanguage = (typeof OUTREACH_LANGUAGES)[number];
