export interface LinkedInLeadsQueryConfig {
    keywords?: string;
    seniority?: string[];
    departments?: string[];
    location?: string[];
    companyIndustries?: string[];
    company_size?: string[];
    company_location?: string[];
    company_revenue?: string[];
    limit?: number;
    only_with_email?: boolean;
}

export interface LinkedInLeadsRawItem {
    Name?: string;
    'First Name'?: string;
    'Last Name'?: string;
    Email?: string;
    'Email Domain'?: string;
    'Job Title'?: string;
    Seniority?: string;
    Department?: string;
    City?: string;
    State?: string;
    Country?: string;
    LinkedIn?: string;
    'Company Name'?: string;
    'Company Domain'?: string;
    'Company Industry'?: string;
    'Company Sub Industry'?: string;
    'Company Location'?: string;
    'Company LinkedIn'?: string;
    firstName?: string;
    lastName?: string;
    fullName?: string;
    name?: string;
    email?: string;
    workEmail?: string;
    personalEmail?: string;
    phone?: string;
    phoneNumber?: string;
    title?: string;
    jobTitle?: string;
    company?: string;
    companyName?: string;
    companyDomain?: string;
    companyWebsite?: string;
    website?: string;
    linkedinUrl?: string;
    linkedinProfileUrl?: string;
    profileUrl?: string;
    location?: string;
    city?: string;
    state?: string;
    country?: string;
    industry?: string;
    headline?: string;
    summary?: string;
    [key: string]: any;
}
