export const DEPARTMENTS = [
    "Admin",
    "Analytics",
    "Applications",
    "Cloud",
    "Compliance",
    "Controller",
    "Customer Service",
    "Cyber Security",
    "Data Engineering",
    "Devops",
    "Digital",
    "Distribution",
    "Engineering",
    "Finance",
    "Fraud",
    "Hiring",
    "HR",
    "Infrastructure",
    "Inside Sales",
    "IT",
    "Learning",
    "Legal",
    "Marketing",
    "Network Security",
    "Operations",
    "Product Management",
    "Product Security",
    "Production",
    "Purchase",
    "Research",
    "Risk",
    "Sales",
    "Security",
    "Support",
    "Testing",
    "Training",
] as const;

export type Department = (typeof DEPARTMENTS)[number];
