export const FUNDING_TYPES = [
    "Venture Round",
    "Angel Round",
    "Convertible Note",
    "Corporate Round",
    "Debt Financing",
    "Funding Round",
    "Grant",
    "Initial Coin Offering",
    "Non Equity Assistance",
    "Private Equity Round",
    "Product Crowdfunding",
    "Secondary Market",
    "Pre Seed Round",
    "Seed Round",
    "Post",
    "Post-IPO Debt",
    "Post-IPO Equity",
    "Post-IPO Secondary",
    "Series A",
    "Series B",
    "Series C",
    "Series D",
    "Series E",
    "Series F",
    "Series G",
    "Series H",
    "Series I",
    "Series J",
] as const;

export type FundingType = (typeof FUNDING_TYPES)[number];
