export const ApiRoutes = {
    auth: {
        email: {
            login: "/auth/email/login",
            register: "/auth/email/register",
            refresh_token: "/auth/email/refresh-token",
            admin_login_to_account: (account_uuid: string) => `/auth/email/${account_uuid}/admin-login`,
            forgot_password: "/auth/forgot-password",
            reset_password: "/auth/reset-password",
            verify_email: "/auth/verify-email",
            resend_verification_email: "/auth/resend-verification-email",
        },
    },
    users: {
        prefix: "/users",
        me: "/users/me",
    },
    google_maps: {
        timezone: "/google-maps/timezone",
    },
    leads: {
        prefix: "/leads",
        list: "/leads",
        get: (uuid: string) => `/leads/${uuid}`,
        enrichments: (uuid: string) => `/leads/${uuid}/enrichments`,
        enrich: (uuid: string) => `/leads/${uuid}/enrich`,
    },
    contacts: {
        prefix: "/contacts",
        list: "/contacts",
        create: "/contacts",
        get: (uuid: string) => `/contacts/${uuid}`,
        update: (uuid: string) => `/contacts/${uuid}`,
        remove: (uuid: string) => `/contacts/${uuid}`,
        update_status: (uuid: string) => `/contacts/${uuid}/status`,
        update_tags: (uuid: string) => `/contacts/${uuid}/tags`,
        add_note: (uuid: string) => `/contacts/${uuid}/notes`,
        interactions: (uuid: string) => `/contacts/${uuid}/interactions`,
        score: (uuid: string) => `/contacts/${uuid}/score`,
        draft_messages: (uuid: string) => `/contacts/${uuid}/draft-messages`,
        enrich: (uuid: string) => `/contacts/${uuid}/enrich`,
        messages: (uuid: string) => `/contacts/${uuid}/messages`,
        from_lead: (lead_uuid: string) => `/contacts/from-lead/${lead_uuid}`,
    },
    outreach: {
        list_messages: "/outreach/messages",
        update_message: (uuid: string) => `/outreach/messages/${uuid}`,
        send_message: (uuid: string) => `/outreach/messages/${uuid}/send`,
        delete_message: (uuid: string) => `/outreach/messages/${uuid}`,
    },
    dashboard: {
        prefix: "/dashboard",
        stats: "/dashboard/stats",
        top_contacts: "/dashboard/top-contacts",
        pending_drafts: "/dashboard/pending-drafts",
    },
    filters: {
        prefix: "/filters",
        list: "/filters",
        create: "/filters",
        get: (uuid: string) => `/filters/${uuid}`,
        update: (uuid: string) => `/filters/${uuid}`,
        remove: (uuid: string) => `/filters/${uuid}`,
        run: (uuid: string) => `/filters/${uuid}/run`,
        jobs: (uuid: string) => `/filters/${uuid}/jobs`,
    },
    sender_profiles: {
        prefix: "/sender-profiles",
        list: "/sender-profiles",
        create: "/sender-profiles",
        get: (uuid: string) => `/sender-profiles/${uuid}`,
        update: (uuid: string) => `/sender-profiles/${uuid}`,
        remove: (uuid: string) => `/sender-profiles/${uuid}`,
    },
}